USER-SUPPLIED VALUES:
argo:
  autosync: true
  clusterDomain: kind.internal
  clusterName: dev
  deployRepoRevision: my-dev-config
  deployRepoURL: https://github.com/kbanaszc/edge-manageability-framework
  namespace: dev
  o11y:
    sre:
      customerLabel: local
  orchestratorVersion: v2025.2.0
  project: dev
  targetServer: https://kubernetes.default.svc
orchestratorDeployment:
  argoServiceType: LoadBalancer
  enableMailpit: true
  targetCluster: kind
postCustomTemplateOverwrite:
  traefik:
    logs:
      general:
        level: DEBUG
root:
  clusterValues:
  - orch-configs/profiles/enable-platform.yaml
  - orch-configs/profiles/enable-o11y.yaml
  - orch-configs/profiles/enable-audit.yaml
  - orch-configs/profiles/enable-kyverno.yaml
  - orch-configs/profiles/enable-app-orch.yaml
  - orch-configs/profiles/enable-cluster-orch.yaml
  - orch-configs/profiles/enable-edgeinfra.yaml
  - orch-configs/profiles/enable-full-ui.yaml
  - orch-configs/profiles/enable-dev.yaml
  - orch-configs/profiles/enable-sre.yaml
  - orch-configs/profiles/proxy-none.yaml
  - orch-configs/profiles/profile-dev.yaml
  - orch-configs/profiles/artifact-rs-production-noauth.yaml
  - orch-configs/profiles/o11y-dev.yaml
  - orch-configs/profiles/alerting-emails-dev.yaml
  - orch-configs/profiles/resource-default.yaml
  - orch-configs/profiles/enable-metrics.yaml
  - orch-configs/clusters/dev.yaml
  useLocalValues: true
